### ISSUE TITLE
does not work if url has & in it

### ISSUE THREAD

**Issue by junaidk** [p1rox/Youtube-dl-WebUI#19]
if url has `&` in its one of argument values, it does not do any thing. It does not even show error.
example url : `https://www.youtube.com/watch?t=42&v=f3ZOqa_UUQ8`

If we run youtube-dl command from command line with given url, the `&` in argument value send process in background url received by command becomes  `https://www.youtube.com/watch?t=42` .

So url should be provided in single quotes to youtube-dl command.
`youtube-dl 'https://www.youtube.com/watch?t=42&v=f3ZOqa_UUQ8'`

**Comment by danog** [comment]
Just fixed this in #22.
